# Generated by Django 4.1.1 on 2022-12-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_me_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name_private',
            field=models.BooleanField(default=False),
        ),
    ]
