# Generated by Django 4.1.1 on 2022-11-24 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatterapp', '0006_alter_room_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MessageFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField(null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatterapp.message')),
            ],
        ),
    ]
